name: Create Badges
on:
  workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: peternied/opensearch-build-badger@main
      with:
        versions: "1.3.7, 2.3, 3.0"
    - uses: peternied/opensearch-build-badger@main
      with:
        versions: "3.0, 2.4"
        repository: "security"
